package main

import (
	"strings"
	"testing"
)

// TestSplitResolvers covers the difference between a host that runs
// systemd-resolved and one that does not. The resolved stub (127.0.0.53) is
// only reachable inside the host's network namespace, so it must be filtered
// out before it is written into a container.
func TestSplitResolvers(t *testing.T) {
	cases := []struct {
		name     string
		contents string
		usable   []string
		skipped  []string
	}{
		{
			name:     "systemd-resolved",
			contents: "# Generated by systemd-resolved\nnameserver 127.0.0.53\noptions edns0 trust-ad\n",
			skipped:  []string{"127.0.0.53"},
		},
		{
			name:     "tailscale",
			contents: "nameserver 100.100.100.100\nnameserver fd7a:115c:a1e0::53\n",
			usable:   []string{"100.100.100.100", "fd7a:115c:a1e0::53"},
		},
		{
			name:     "networkmanager with a router",
			contents: "nameserver 192.168.1.1\nnameserver 8.8.8.8\n",
			usable:   []string{"192.168.1.1", "8.8.8.8"},
		},
		{
			name:     "mixed",
			contents: "nameserver 127.0.0.53\nnameserver 1.1.1.1\nnameserver ::1\n",
			usable:   []string{"1.1.1.1"},
			skipped:  []string{"127.0.0.53", "::1"},
		},
		{
			name:     "empty",
			contents: "",
		},
		{
			name:     "malformed lines are ignored",
			contents: "search example.com\nnameserver\nnameserver not-an-ip\n",
			usable:   []string{"not-an-ip"},
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			usable, skipped := splitResolvers(c.contents)
			if strings.Join(usable, ",") != strings.Join(c.usable, ",") {
				t.Errorf("usable = %v, want %v", usable, c.usable)
			}
			if strings.Join(skipped, ",") != strings.Join(c.skipped, ",") {
				t.Errorf("skipped = %v, want %v", skipped, c.skipped)
			}
		})
	}
}
