package vm

import (
	"strings"
	"testing"

	"github.com/common-creation/sandboxxing/internal/config"
)

func TestCompilePattern(t *testing.T) {
	re, err := compilePattern("web-*")
	if err != nil {
		t.Fatal(err)
	}
	if !re.MatchString("web-1") || re.MatchString("db-1") {
		t.Error("wildcard pattern does not match as expected")
	}
	if re, err := compilePattern(""); err != nil || re != nil {
		t.Error("empty pattern must match everything")
	}
	if re, err := compilePattern("*"); err != nil || re != nil {
		t.Error("'*' must match everything")
	}
	if re, err = compilePattern("a?c"); err != nil || !re.MatchString("abc") {
		t.Error("'?' must match one character")
	}
}

func TestApplyDefaults(t *testing.T) {
	cfg := config.Default()
	m := &Manager{cfg: cfg}
	opts := &Options{}
	m.applyDefaults(opts)
	if opts.Image != cfg.Image {
		t.Errorf("image = %q, want %q", opts.Image, cfg.Image)
	}
	if opts.CPU != cfg.DefaultCPU {
		t.Errorf("cpu = %d, want %d", opts.CPU, cfg.DefaultCPU)
	}
	if opts.Memory != int64(cfg.DefaultMemory) || opts.Disk != int64(cfg.DefaultDisk) {
		t.Error("memory and disk defaults were not applied")
	}

	custom := &Options{CPU: 8, Memory: 1 << 30, Disk: 2 << 30, Image: "other"}
	m.applyDefaults(custom)
	if custom.CPU != 8 || custom.Memory != 1<<30 || custom.Disk != 2<<30 || custom.Image != "other" {
		t.Error("explicit values must not be overwritten")
	}
}

// TestResolvConfPrefersConfiguration verifies that an explicit dns list wins
// over the resolvers of the host.
func TestResolvConfPrefersConfiguration(t *testing.T) {
	m := &Manager{cfg: &config.Config{DNS: []string{"9.9.9.9", "1.1.1.1"}}}
	got := m.resolvConf()
	if !strings.Contains(got, "nameserver 9.9.9.9") || !strings.Contains(got, "nameserver 1.1.1.1") {
		t.Errorf("configured resolvers missing:\n%s", got)
	}
	if strings.Contains(got, "127.0.0.53") {
		t.Errorf("the host stub leaked into the container:\n%s", got)
	}
}

// TestResolvConfFallsBackWhenHostUsesResolved covers the failure seen on a
// host running systemd-resolved: /etc/resolv.conf only names 127.0.0.53, and
// the container has no resolver on that address.
func TestResolvConfFallsBackWhenHostUsesResolved(t *testing.T) {
	if got := isLoopbackResolver("127.0.0.53"); !got {
		t.Error("127.0.0.53 must be treated as a host only resolver")
	}
	for _, addr := range []string{"1.1.1.1", "8.8.8.8", "2606:4700:4700::1111"} {
		if isLoopbackResolver(addr) {
			t.Errorf("%s must be usable", addr)
		}
	}
}

// TestResolvConfRendering checks the file that is written into the container.
func TestResolvConfRendering(t *testing.T) {
	m := &Manager{cfg: &config.Config{DNS: []string{"10.0.0.53"}}}
	got := m.resolvConf()
	if !strings.HasPrefix(got, "# generated by sandboxxing") {
		t.Errorf("missing header:\n%s", got)
	}
	if !strings.HasSuffix(got, "nameserver 10.0.0.53\n") {
		t.Errorf("unexpected ending:\n%s", got)
	}
}
